#!/usr/bin/env bun

import { app, $ } from "@gutenye/script.js";

const HELP = `
ake t all
ake t exported
ake t requirefix
ake t remaining
ake t password
`;

app.help(HELP);

const CLI = "bun run cli";

app.cmd("l", "Lint").add(async () => {
  await $`bun run lint`;
});

app.cmd("t", "Lint and run tests").add(async ({ argv }) => {
  await app.invoke("l");
  await $`bun run test ${argv}`;
});

app
  .cmd("edit", "Edit file without user config")
  .add("<path>", "Path", ["$files"])
  .add(async (path) => {
    await $`vi -u NONE -U NONE ${path}`;
  });

app.cmd("t watch", "Run tests in watch mode").add(async ({ argv }) => {
  await $`bun run test --watch ${argv}`;
});

app.cmd("t reset", "Reset test fixtures").add(async () => {
  await $`
    cp src/__tests__/fixtures/bitwarden.json data
    cp src/__tests__/fixtures/bitwardenEncrypted.json data
  `;
});

app.cmd("t manual", "Run manual bitwarden->apple conversion").add(async () => {
  await $`${CLI} convert bitwarden-to-apple src/__tests__/fixtures/bitwarden.json data/output.csv --skip-fields skip`;
});

// Summary: exported + requirefix + remaining
app.cmd("t all", "Convert all entries").add(async () => {
  await $`${CLI} convert bitwarden-to-apple src/__tests__/fixtures/bitwarden.json data/output.csv --include-types login`;
});

// Summary: exported
app.cmd("t exported", "Convert exported entries").add(async () => {
  await $`${CLI} convert bitwarden-to-apple src/__tests__/fixtures/bitwarden.json data/output.csv`;
});

// Summary: exported + requirefix
app.cmd("t requirefix", "Convert requirefix entries").add(async () => {
  await $`${CLI} convert bitwarden-to-apple src/__tests__/fixtures/bitwarden.json data/output.csv`;
});

// Summary: exported + reamining
app.cmd("t remaining", "Convert remaining entries").add(async () => {
  await $`${CLI} convert bitwarden-to-apple src/__tests__/fixtures/bitwarden.json data/output.csv --include-uris foo.com`;
});

app.cmd("t password", "Convert password entries").add(async () => {
  await $`${CLI} convert bitwarden-to-apple src/__tests__/fixtures/bitwardenEncrypted.json data/output.csv`;
});

app
  .cmd("convert", "Convert")
  .add("[includeUris]", "Include URIs")
  .add(async (includeUris) => {
    const base = `${CLI} convert bitwarden-to-apple data/bitwarden.json data/output.csv`;
    if (includeUris) {
      await $`${base} --include-uris ${includeUris}`;
    } else {
      await $`${base}`;
    }
  });
